<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: mysqli::__construct(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in D:\Projects2025\etusuladmin\settings.php on line <i>23</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>362416</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='D:\Projects2025\etusuladmin\settings.php' bgcolor='#eeeeec'>...\settings.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.0488</td><td bgcolor='#eeeeec' align='right'>422192</td><td bgcolor='#eeeeec'>checkDB( <span>$dbuser = </span><span>NULL</span>, <span>$dbpass = </span><span>NULL</span>, <span>$dbname = </span><span>NULL</span> )</td><td title='D:\Projects2025\etusuladmin\settings.php' bgcolor='#eeeeec'>...\settings.php<b>:</b>48</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.0488</td><td bgcolor='#eeeeec' align='right'>422576</td><td bgcolor='#eeeeec'><a href='http://www.php.net/mysqli.construct' target='_new'>__construct</a>( <span>$hostname = </span><span>&#39;localhost&#39;</span>, <span>$username = </span><span>NULL</span>, <span>$password = </span><span>NULL</span>, <span>$database = </span><span>NULL</span> )</td><td title='D:\Projects2025\etusuladmin\settings.php' bgcolor='#eeeeec'>...\settings.php<b>:</b>23</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: mysqli object is already closed in D:\Projects2025\etusuladmin\settings.php on line <i>25</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: mysqli object is already closed in D:\Projects2025\etusuladmin\settings.php on line <i>25</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>362416</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='D:\Projects2025\etusuladmin\settings.php' bgcolor='#eeeeec'>...\settings.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.0488</td><td bgcolor='#eeeeec' align='right'>422192</td><td bgcolor='#eeeeec'>checkDB( <span>$dbuser = </span><span>NULL</span>, <span>$dbpass = </span><span>NULL</span>, <span>$dbname = </span><span>NULL</span> )</td><td title='D:\Projects2025\etusuladmin\settings.php' bgcolor='#eeeeec'>...\settings.php<b>:</b>48</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>4.1307</td><td bgcolor='#eeeeec' align='right'>424128</td><td bgcolor='#eeeeec'><a href='http://www.php.net/mysqli.close' target='_new'>close</a>(  )</td><td title='D:\Projects2025\etusuladmin\settings.php' bgcolor='#eeeeec'>...\settings.php<b>:</b>25</td></tr>
</table></font>